### ISSUE TITLE
Talk : Playing with partitions using Gparted

### ISSUE THREAD

**Issue by HimanshiJain** [LinuxChixIndia/talks#1]
In this talk, starting with the basic information about partitions(eg. logical and physical partitions), file system in Linux and introduction to Gparted, I would actually tell how the different partitions can be moved/resized/copied/changed using Gparted.

**Comment by CuriousLearner** [comment]
Hi @HimanshiJain 
Can you please update your slides/video here?

**Comment by HimanshiJain** [comment]
Yes sure!
Following is the Google drive link for slides:
https://docs.google.com/presentation/d/1-uirLJ9HPTCvKoY-
7Op1vZWaZPlKb8JxQLwWfy-yL_c/edit?usp=drivesdk .
Do you want me to add any relevant links for the same that I had used? If
yes I will update by tomorrow.

**Comment by CuriousLearner** [comment]
@HimanshiJain Can you please make that publically acessible?

**Comment by HimanshiJain** [comment]
I have set its share rights to 'Anyone with the link can view'. Should I
change  it to edit?

**Comment by CuriousLearner** [comment]
@HimanshiJain Can you please post the url again?

**Comment by HimanshiJain** [comment]
Yes sure! 
https://drive.google.com/open?id=1-uirLJ9HPTCvKoY-7Op1vZWaZPlKb8JxQLwWfy-yL_c

**Comment by CuriousLearner** [comment]
@HimanshiJain Thanks!

**Comment by CuriousLearner** [comment]
Added to `README` in 1902843
