### ISSUE TITLE
Linux Directory Structure and Linux Security

### ISSUE THREAD

**Issue by vijaykrishnavanshi** [LinuxChixIndia/talks#10]
**Abstract**

Talk will be focused on the Linux Directory Structure and Linux Security. 

**About**

This talk will give some insight to why a directory structure is a big deal and which one should you choose. Talk will somewhat be divided into two parts first one will cover things about the directory structure and the other one will describe security aspects in Linux system. The second part of the talk will also offer you tips on how you can secure it. We will try to keep the talk as practical as possible :)

**Pre-requisites**

Keen interest to Linux will do :)

**Expected duration**

Maximum 1 Hour

**Level**

Intermediate

**Resources**

If you want to try what we will tell you, get your machines with Linux installed.

**Speaker Bio**

Vijay Krishnavanshi 
Google Summer of Code Student 2017( KDE )
email: vijaykrishnavanshi@gmail.com

Abhishek Bundela 
Bug Hunter and Security Enthusiast
twitter: @abhibundela

Link to Slides: http://slides.com/vijaykrishnavanshi/hello

**Comment by Pulkit07** [comment]
I wish I can attend this. @shivan1b Ma'am can you please stream this live? :smile_cat:

**Comment by shivan1b** [comment]
@Pulkit07 We can go live for sometime on Facebook and Twitter. ;)

**Comment by vijaykrishnavanshi** [comment]
Updated the links to slides.

**Comment by CuriousLearner** [comment]
Thank @vijaykrishnavanshi !

**Comment by CuriousLearner** [comment]
Added to `README` in 1902843
