### ISSUE TITLE
How to be a lazier developer

### ISSUE THREAD

**Issue by rajat404** [LinuxChixIndia/talks#11]
**Abstract**

This talk is largely going to cover shell configuration management.

**About**

I'll be talking about various terminal emulators, shells, configuration managers and how one can get more done with less effort.

The following topics shall be covered:
- Terminal Emulators
- Bash & Zsh
- Functions & Aliases
- Shell Configuration Managers
- Environment Variables
- Dotfiles

**Pre-requisites**

Elementary knowledge of *NIX systems is all one needs to comprehend this talk. 

It'd be pertinent for the attendees to bring their laptops running any *NIX distribution, as I'd prefer to keep the session interactive.

**Expected duration**

30-40 minutes

**Level**

Beginner

**Resources**

Slides: http://slides.com/rajat404/shell_config
Blog Post: https://medium.com/@rajat404/dev-setup-terminal-a0a3a23db47c

**Speaker Bio**

Rajat is an active member of the python community, and has been volunteering for PyCon India since last 5 years. He has been earning his bread and butter writing code in python for the last 2 years. You can find him online(twitter, github, telegram) by his handle @rajat404

**Comment by rajat404** [comment]
Links to slides & accompanying blog post added. Cheers!

**Comment by CuriousLearner** [comment]
Thanks @rajat404 !

**Comment by CuriousLearner** [comment]
Added to `README` in 1902843
