### ISSUE TITLE
Linux Networking 101 

### ISSUE THREAD

**Issue by Warlord77** [LinuxChixIndia/talks#13]
**Abstract**

_A brief overview of what your talk is about_

**About**
Linux Networking 101

**Pre-requisites**

- Linux based system

**Expected duration**

- 20 - 30 minutes

**Level** 

Beginner

**Resources**

_Add links to resources which can further be used to read up on the topic_

**Speaker Bio**

_Write a brief decription about you here_

###### - Can be done after the talk/workshop -

[Include link to slides here](link)

[Include link to video here](link)

**Comment by CuriousLearner** [comment]
Hi @Warlord77 

Can you please fill up the details? These sections were made to guide speakers to fill in the details needed.

**Comment by CuriousLearner** [comment]
@Warlord77   Can you please give a link to the slides and other reference materials?

**Comment by CuriousLearner** [comment]
Hi @Warlord77, Just wanted to ping you to know about the status of slides/reference materials.

Can you please update them?

**Comment by CuriousLearner** [comment]
@Warlord77 Just wanted to ping you for the slides/reference materials for your talk, so that they can be updated in the repo. Can you please update it here?
