### ISSUE TITLE
Linux Network Configuration and Troubleshooting Commands

### ISSUE THREAD

**Issue by nupuragrahari** [LinuxChixIndia/talks#14]
**Abstract**

The talk is about a few useful Linux Network Configuration and Troubleshooting Commands. Explaining the usage and purpose of each of these commands.

**Pre-requisites**

Linux based system

**Expected duration**

20-25 minutes

**Level**

Beginner

**Speaker Bio**

A linux user, an open source enthusiast,currently working with javascript.

**Comment by CuriousLearner** [comment]
@nupuragrahari   Can you please give a link to the slides and other reference materials?

**Comment by nupuragrahari** [comment]
https://docs.google.com/presentation/d/1bAXFgUSfaCpQ9Ce9bwLld7Yb5ySpBOSj9SxexNlMLzc/edit?usp=sharing

https://www.tecmint.com/linux-network-configuration-and-troubleshooting-commands/

https://www.computerhope.com/unix/utelnet.htm

**Comment by CuriousLearner** [comment]
Thanks for the update @nupuragrahari !
