### ISSUE TITLE
How NAT works

### ISSUE THREAD

**Issue by shivan1b** [LinuxChixIndia/talks#15]
**Abstract**

This talk will cover about the need for bringing NAT and the future prospects.

**About**

Everybody hears and reads about NAT. Ever wondered how does it work? This talk is going to cover about NAT as a concept, the need of bringing it in and the future prospects given the rise of IPv6.

**Pre-requisites**

None

**Expected duration**

30 minutes

**Level**

_Beginner_

**Resources**

[How many devices can share a Wi-Fi network](https://www.lifewire.com/how-many-devices-can-share-a-wifi-network-818298)

[How NAT works](http://computer.howstuffworks.com/nat.htm)

**Speaker Bio**

[Shivani Bhardwaj](https://about.me/shivani.bhardwaj)

**Slides**

[How NAT works by Shivani Bhardwaj](http://slides.com/shivanibhardwaj/how-nat-works#/)

**Comment by CuriousLearner** [comment]
Still needs to be updated on `README`
