### ISSUE TITLE
Netlink Sockets : A way to communicate with kernel

### ISSUE THREAD

**Issue by mysticTot** [LinuxChixIndia/talks#16]
**Abstract**

Netlink socket family is an inter process communication mechanism for communication b/w kernel and user space.

**About**
A short intro to netlink sockets, their applications and libraries etc. See  udev and iproute2 utilities. 

**Pre-requisites**
None

**Expected duration**
30 minutes

**Level**
Beginner

**Resources**

https://en.wikipedia.org/wiki/Netlink

**Speaker Bio**
One out of 7.3 billion  people on earth. 

###### - Can be done after the talk/workshop -

[Include link to slides here](link)

[Include link to video here](link)

**Comment by CuriousLearner** [comment]
@mysticTot  Can you please give a link to the slides and other reference materials?

**Comment by mysticTot** [comment]
I don't have slides but I'll upload a text file containing summary and some useful links.
Thanks

**Comment by CuriousLearner** [comment]
Thanks, we'll wait for your updates.

**Comment by CuriousLearner** [comment]
@mysticTot Can you please update the material here?

**Comment by CuriousLearner** [comment]
@Warlord77 Just wanted to ping you for the slides/reference materials for your talk, so that they can be updated in the repo. Can you please update it here?
