### ISSUE TITLE
RGSoC and Tessel

### ISSUE THREAD

**Issue by brihijoshi** [LinuxChixIndia/talks#23]
**Abstract**

A brief introduction to what RGSoC (Rails Girls Summer of Code) is, along with application process, work details, project details. 
Then, an introduction to Tessel, our project for RGSoC'17, along with a few technical specifications and live Hardware demos.

**About**

Rails Girls Summer of Code is an award-winning global fellowship program aimed at bringing more diversity into Open Source. Successful applicants are paid a monthly stipend, from July to September, to work on Open Source projects of their choice.

Rails Girls Summer of Code is about helping newcomers to the world of programming further expand their knowledge and skills, by contributing to a worthwhile Open Source project. The focus is not on producing highly sophisticated code, but rather participants learning transferable skills from their project work.

Tessel 2 is a robust IoT and robotics development platform. Leverage all the libraries of Node.JS to create useful devices in minutes with Tessel.

**Pre-requisites**

None

**Expected duration**

30-40 minutes

**Level**

Beginner

**Resources**

https://railsgirlssummerofcode.org/
https://tessel.io/

**Speaker Bio**

We are Brihi Joshi and Shravika Mittal in our Sophomore year of college at IIIT-Delhi. We have been working on Tessel this summer since July 1st. It has been a great experience so far writing our application in February, waiting for the results in May, becoming a part of the RGSoC Community finally and working since then.
Brihi is majoring in Computer Science Engineering and loves to mix and fiddle with creativity in code. She brings in the caffeine-induced, late night coding sessions along with fresh experiments in the team.
Shravika is majoring in Computer Science and Engineering. It's been hardly a year since she's got her hands dirty with programming, and it's already a vital part of her daily schedule. She brings out dedication and hard work in the team.
The Team is an amalgamation of all things tech and electronic. We are a dynamic duo that believes in learning and strengthening concepts while on the way to developing something. Nobody knew that two individuals, who met each other on the first day of the Induction Programme would get along so well that they would end up doing a project together after exploring RGSoC in December 2016.

###### - Can be done after the talk/workshop -

[Slides](https://github.com/276linesofCode/blog-posts/blob/master/LinuxChix-talk/LinuxChix%20talk%20-%2020%252F8%252F2017.pptx)

**Comment by shivan1b** [comment]
Thanks, @brihijoshi! :+1:
