### ISSUE TITLE
Customising your Linux UI using GNOME

### ISSUE THREAD

**Issue by meetsha** [LinuxChixIndia/talks#4]
There are many people who love Linux but over time get bored of its somewhat bland looks. This talk helps you overhaul the UI experience with GNOME. It will cover the following:

- Installing and setting up GNOME.
- Using the GNOME Tweak Tool
- Setting up basic GNOME extensions
- Installing themes and icon packs
- Adding your own shortcuts
- (+ Managing your repositories)

P.s: Ubuntu is officially killing Unity to switch to GNOME Desktop 18.04 onwards. So this talk will help you make the switch easily.

**Comment by CuriousLearner** [comment]
Hi @meetsha 
Can you please update your slides/video here?

**Comment by meetsha** [comment]
https://drive.google.com/file/d/0Bzt1ZPbjYd_2enNfQjZGc0FSd2M/view?usp=sharing
https://pastebin.com/6nqSvWuZ

**Comment by CuriousLearner** [comment]
Thanks @meetsha !

**Comment by CuriousLearner** [comment]
Added to `README` in 1902843
