### ISSUE TITLE
Crash course on Tmux

### ISSUE THREAD

**Issue by Priyal-Trivedi** [LinuxChixIndia/talks#5]
The talk is for the beginners at Linux who require to use the terminal frequently.
Tmux - 'Terminal multiplexer' enables a number of terminals (or windows), each running a separate program, to be created, accessed, and controlled from a single screen. 
Installation and understanding the required key bindings for various actions would be covered by me during the talk.

**Comment by CuriousLearner** [comment]
Hi @Priyal-Trivedi 
Can you please update your slides/video here?

**Comment by Priyal-Trivedi** [comment]
Link to the slides : http://slides.com/priyaltrivedi-1/tmux-terminal-multiplexer#/

**Comment by CuriousLearner** [comment]
Thanks @Priyal-Trivedi !

**Comment by CuriousLearner** [comment]
Added to `README` in 1902843
