### ISSUE TITLE
gdb - Debugging tool for C/C++ programs

### ISSUE THREAD

**Issue by aksh98** [LinuxChixIndia/talks#7]
**gdb** - also called GNU debugger is one of the most popular debugging tools to debug C or C++ programs from the command line. 
This talk will cover all the steps involved in debugging a program. Stepping through the code and finding the error using various techniques like setting up watchpoints, backtracing etc.

It would be a 30 min talk approximately.

**Comment by CuriousLearner** [comment]
@aksh98 Do you have the slides ready? If not, when you have them, can you please update here?

**Comment by aksh98** [comment]
Yeah sure :) I'll upload them soon.

**Comment by aksh98** [comment]
Hi,
Kindly review the attached slides.
Slides: [GNU debugger.pdf](https://github.com/LinuxChixIndia/talks/files/1062188/GNU.debugger.pdf)

**Comment by CuriousLearner** [comment]
@aksh98 LGTM. I hope it would be along with a demo :)

@shivan1b can take a look here.

**Comment by aksh98** [comment]
Yes, I'll present it alongside a demo.

**Comment by shivan1b** [comment]
Please include LinuxChix India logo/name on the front slide. Everything else looks good. All the best! :)

**Comment by CuriousLearner** [comment]
Added to `README` in 1902843
